# Generated by Django 5.2.5 on 2025-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('insurer_name', models.CharField(max_length=255)),
                ('discharge_date', models.DateField()),
            ],
        ),
    ]
