# Generated by Django 5.2.5 on 2025-08-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('cpt_codes', models.CharField(max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='claims.claim')),
            ],
        ),
    ]
