# Generated by Django 5.2.5 on 2025-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetail',
            name='claim_id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
