# Generated by Django 5.2.5 on 2025-08-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimdetail_claim_id_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdetail',
            name='claim_id_original',
        ),
    ]
