# Generated by Django 5.2.5 on 2025-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('note', 'Note'), ('flag', 'Flag for Review')], default='note', max_length=10),
        ),
    ]
