# Generated by Django 5.2.5 on 2025-08-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_note_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_type',
        ),
    ]
