# Generated by Django 5.2.5 on 2025-08-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_systemflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemflag',
            name='reviewed',
        ),
    ]
